config/routes.rb
Rails.application.routes.draw do
 

root 'gigs#index'

  get 'signup',   to: 'users#new',           as: 'signup'
  get 'signin',   to: 'sessions#new',        as: 'signin'
  get 'signout',  to: 'sessions#destroy',    as: 'signout'

get 'gigs' => 'gigs#get'
resources :gigs

get 'sessions/new'
resources :sessions

get 'employers' => 'employers#add'
resources :employers, only: :add

get 'users' => 'users#sign'
resources :users

get 'jobdata' => 'jobdata#start'
resources :jobdata, only: :index



end

app/models/employer.rb
class Employer < ActiveRecord::Base

#associations
has_many :gigs

has_one :user



end

app/models/gig.rb
class Gig < ActiveRecord::Base
  belongs_to :employer
end

app/models/jobdatum.rb
class Jobdatum < ActiveRecord::Base

	#remember to roll back jobdatum Db migration before geting rid if this jobdatum thing
end

app/models/user.rb
class User < ActiveRecord::Base

 

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
class Admin::ApplicationController < Administrate::ApplicationController
  before_filter :authenticate_admin

  def authenticate_admin
    # TODO Add authentication logic here.
  end

  # Override this value to specify the number of elements to display at a time
  # on index pages. Defaults to 20.
  # def records_per_page
  #   params[:per_page] || 20
  # end
end

app/controllers/admin/jobdata_controller.rb
module Admin
  class JobdataController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Jobdatum.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Jobdatum.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
  	@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  	
  end

  helper_method :current_user
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
	def add

		@employers = Employer.all
		
	end
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
	def get

		@gig = Gig.all
		
	end

	def create
		@gig = Gig.new(gig_params)

		if @gig.save
			redirect_to gig_path, notice: "J1 Gig Saved!"
		else
			render 'new', alert: "There was an error."
		end
	end

	def show
		@gig = Gig.find(params[:id])
	end

	def edit
		@gig = Gig.find(params[:id])
	end

	def destroy
		@gig = Gig.find(params[:id])
		@gig.destroy
		redirect_to gig_path, notice: "J1 Gig Deleted" 
	end


	def update
		if @gig.update(gig_params)
			redirect_to gig_path, notice: "J1 Gig Updated!"
		else
			render 'edit', alert: "Something Went Wrong Somewhere - huh?"
		end

	end


private

	def gig_params
		params.require(:gig).permit(:name, :position, :start_date, :pay)
		
	end

	def get_gigs
    @gig = Gig.find(params[:id])
	end
  

end

app/controllers/jobdata_controller.rb
class JobdataController < ApplicationController
	def start
		
	end

	def index

		@jobdatum = Jobdatum.all

	end	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])

	if  user && user.authenticate(params[:password])
		cookies[:auth_token] = user.auth_token
		redirect_to root_path, notice: "Hi, you've sucessfully signed in!"

	else
		flash[:alert] = "Invalid email or password"
		render 'new'

	  end
end

  def destroy 
  	cookies.delete(:auth_token)
  	redirect_to root_path

  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :get_user, only: [:show, :edit, :update, :destroy, ]

	
  def new
    redirect_to root_path if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      cookies.permanent[:auth_token]
      redirect_to root_path, notice: "Welcome to J1 Judes Jobs!"
    else
      render 'new'
  end 

end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path(@user), notice: "Your account has been updated."
    else
      render "edit"
    end
    
  end

  def destroy
    @user.destroy
    redirect_to signout_path, notice: "Your acccount has been deleted."
    
  end

private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def get_user

    @user = current_user
    
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/jobdata_helper.rb
module JobdataHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employers/add.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>
 <div><%= render "layouts/nav" %></div>
 
    <div class="row">
      <div class="large-12 columns">
        <h1>Judes' J1 Jobs List</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout large">
          <h3>ADD EMPLOYERS </h3>
          <div>
	


  <H4> LIST of stuff done or to be done for Judes Jobs </h4>

  <ul> 3 Models employer gig user</ul>
  <ul> Models Views Controllers MVC </ul>
  <ul> Controllers and Def actions for each </ul>
    <ul> Empoyers has an ADD page  </ul>
      <ul> Controllers and Def actions for each </ul>
        <ul> Controllers and Def actions for each </ul>
  <ul> Setup Simple Form installed with Foundation) https://github.com/plataformatec/simple_form  </ul>
	<ul>Login Setup Users </ul>
	
	<ul> Views for new models </ul>
	<ul> Controllers for new Models</ul>
	<ul> Yield for top navbar </ul>
	<ul> resources :jobsdata </ul>
<ul> http://guides.rubyonrails.org/asset_pipeline.html</ul>

</div>

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

app/views/employers/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>

    <div class="row">
      <div class="large-12 columns">
        <h1>Judes' J1 Jobs List</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout large">
          <h3>Employers ADD page </h3>
          <div>
	<h2> ADD PAGE EMPLOYERS </h2>

	<p> LIST of stuff done or to be done for Judes Jobs </p>

	<ul> 3 Models employer gig user</ul>
	<ul> Models Views Controllers MVC </ul>
	<ul> Controllers and Def actions for each </ul>
    <ul> Empoyers has an ADD page  </ul>
      <ul> Controllers and Def actions for each </ul>
        <ul> Controllers and Def actions for each </ul>
	<ul> Setup Simple Form installed with Foundation) https://github.com/plataformatec/simple_form  </ul>
	<ul>Login Setup Users </ul>
	<ul> display and search for gigs using the datatables plugin http://www.datatables.net/ </ul>
	<ul> Views for new models </ul>
	<ul> Controllers for new Models</ul>
	<ul> Yield for top navbar </ul>
	<ul> resources :jobsdata </ul>
<ul> http://guides.rubyonrails.org/asset_pipeline.html</ul>

</div>

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

app/views/gigs/get.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>
 <%= render "layouts/nav" %>
 
    <div class="row">
      <div class="large-12 columns">
        <h1>Judes' J1 Jobs List</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout large">
          <h3>Get  J1 Summer Gig </h3>
          <div>
	<h2> <%= debug @movie %>  </h2>

<ul> display and search for gigs using the datatables plugin http://www.datatables.net/ </ul>
<ul> ADD some data to DB how?</ul>
	<ul> View Search Gigs on this page</ul>
	<ul> Navbar add as partial  </ul>
	<ul> Add the Data plugin </ul>
    <ul> Sign up in out  </ul>
      <ul> Search Display </ul>
      <ul> Apply for job</ul>
        <ul> Users needs a function - simple form logins bcrypt gem</ul>
	

</div>

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

app/views/gigs/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>
 <%= render "layouts/nav" %>
 
    <div class="row">
      <div class="large-12 columns">
        <h1>Judes' J1 Jobs List</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout large">
          <h3>Get  J1 Summer Gig </h3>
          <div>
	<h2> <%= debug @movie %>  </h2>

<ul> display and search for gigs using the datatables plugin http://www.datatables.net/ </ul>
<ul> ADD some data to DB how?</ul>
	<ul> View Search Gigs on this page</ul>
	<ul> Navbar add as partial  </ul>
	<ul> Add the Data plugin </ul>
    <ul> Sign up in out  </ul>
      <ul> Search Display </ul>
      <ul> Apply for job</ul>
        <ul> Users needs a function - simple form logins bcrypt gem</ul>
	

</div>

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

app/views/jobdata/about.html.erb
about.html.erb

app/views/jobdata/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>

    <div class="row">
      <div class="large-12 columns">
        <h1>Judes' J1 Jobs List</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout large">
          <h3>Index Page Root </h3>
          <div>
	<h2> </h2>

	<p> LIST of stuff to be done in a bullet list</p>

	<ul> Page Plan </ul>
	<ul> Models Views Controllers MVC </ul>
	<ul>  </ul>
	<ul> Setup Simple Form (installed with Foundation) </ul>
	<ul>Login Setup Users </ul>
	<ul> display and search for gigs using the data plugin </ul>
	<ul> Views for new models </ul>
	<ul> Controllers for new Models</ul>
	<ul> Yield for top navbar </ul>
	<ul> resources :jobsdata </ul></div

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

app/views/jobdata/start.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Judes J1 Jobs| Welcome</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>
 <%= render "layouts/nav" %>
    <div class="row">
      <div class="large-12 columns">
        <h1>Judes J1 Jobs| Welcome Page</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout large">
          <h3>JUDES Start Page </h3>

        
	<ul> Add Form - simple form </ul>
	<ul>Login Setup Users - gem Clearance or Devise - BCRYPT install it </ul>
	<ul> display jobs @jobs = Jobs.all</ul>
	<ul>Search Database for jobs </ul>
		<ul> M V C - views and controllers Def Routes /ul>
	<ul> design</ul>

	<ul>Foundation</ul> 
	 <ul>Asset pipeline - add the css and javascripts </ul>
	<ul> Yield </ul>
	<ul> resources :jobsdata </ul>
	<ul> add more inforamtion data to model </ul>
	<ul> singular jobdatum  | plural jobdata  </ul>
	<ul> gems - </ul>
	<ul> resources :jobsdata </ul>
      	<ul> add a Navbar and login logout sigin and out functionality - Rat report methods </ul>  
        

    <div class="row">
      <div class="large-8 medium-8 columns">
        <h5>Here&rsquo;s your basic grid:</h5>
        <!-- Grid Example -->

       
        <hr />

        <h5>ADD a Gig </h5>
        <form>
          <div class="row">
            <div class="large-12 columns">
              <label>Input Label</label>
              <input type="text" placeholder="large-12.columns" />
            </div>
          </div>
          <div class="row">
            <div class="large-4 medium-4 columns">
              <label>Input Label</label>
              <input type="text" placeholder="large-4.columns" />
            </div>
            <div class="large-4 medium-4 columns">
              <label>Input Label</label>
              <input type="text" placeholder="large-4.columns" />
            </div>
            <div class="large-4 medium-4 columns">
              <label>Input Label</label>
              <div class="input-group">
                <input type="text" placeholder="small-9.columns" class="input-group-field" />
                <span class="input-group-label">.com</span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="large-12 columns">
              <label>Select Box</label>
              <select>
                <option value="husker">Server</option>
                <option value="starbuck">Waiter</option>
                <option value="hotdog">Barkeep</option>
                <option value="apollo">Potatoe Peeler</option>
              </select>
            </div>
          </div>
          <div class="row">
            <div class="large-6 medium-6 columns">
              <label>Choose Your Favorite</label>
              <input type="radio" name="pokemon" value="Red" id="pokemonRed"><label for="pokemonRed">Radio 1</label>
              <input type="radio" name="pokemon" value="Blue" id="pokemonBlue"><label for="pokemonBlue">Radio 2</label>
            </div>
            <div class="large-6 medium-6 columns">
              <label>Check these out</label>
              <input id="checkbox1" type="checkbox"><label for="checkbox1">Checkbox 1</label>
              <input id="checkbox2" type="checkbox"><label for="checkbox2">Checkbox 2</label>
            </div>
          </div>
          <div class="row">
            <div class="large-12 columns">
              <label>Textarea Label</label>
              <textarea placeholder="small-12.columns"></textarea>
            </div>
          </div>
        </form>
      </div>

   

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

app/views/layouts/_nav.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Judes J1 Jobs</li>
      <li><%= link_to "Gigs", gigs_path  %></li>
     <li> <%  if !current_user  %></li> <!--  ...this  line is breaking my code -->

  <li><%= link_to "Sign In", signin_path %></li>
  <li><%= link_to "Sign Up", signup_path %></li>

      <% else %>

     <li> <%= link_to "My Profile", edit_user_path(current_user) %> </li>
    <li>  <%= link_to "Sign Out", signout_path %> </li>
    <% end %> 

    </ul>
  </div>

  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Judes J1 jobs and gigs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="row">
	<div class= "small-12 columns">

		<h1>Sign Up</h1>

		<%= simple_form_for @user do |f|%>
		<%= f.input :email %>
		<%= f.input :password %>
		<%= f.input :password_confirmation %>
		<%= f.submit "Sign Up" %>

		<% end %>

	</div>
</div>

app/views/users/sign.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome | Sign In</title>
    <link rel="stylesheet" href="css/foundation.css" />
    <link rel="stylesheet" href="css/app.css" />
  </head>
  <body>
    <div><%= render "layouts/nav" %></div>
 

    <div class="row">
      <div class="large-12 columns">
        <h1>Judes' J1 Jobs List</h1>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <div class="callout large">
          <h3>SIGN IN SIMPLE FORM </h3>
          <div>
	<p> Add sign in Nav Bar to this page </p>
<ul> Sign in bcrypt stuff</ul>


	

</div>

    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/what-input.min.js"></script>
    <script src="js/foundation.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>